#!/bin/bash
SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
NUTS_BASE=$SCRIPT_DIR/../../nuts
V=0.8.6.0
echo NUTS_BASE=$NUTS_BASE
cd $NUTS_BASE
pwd
java -jar -Dnuts.args="-ZyS -w=dev" $SCRIPT_DIR/nuts-release-tool/target/nuts-release-tool-$V.jar
